# Navigation Links
main:
  - name: Bio
    url: /
    weight: 10
  - name: Blog
    url: blog/
    weight: 15
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
